# user variables, change this to make custom site.

name: My Blog
desc: Yet another simple theme for Jekyll.
author:
  name: Kyeonghee Seo
  avatar:
  profile: |
    2018.01 NHN엔터테인먼트 입사
      - 2018.01 현재 기술직군 신입사원
  socials:
    facebook:
    twitter:
    google-plus:
    github: //github.com/algedian
    stack-overflow:
    instagram:
    pinterest:
    steam:
license: MIT License

disqus: "khseo"

# theme variables, change this to make site looks best.
baseurl: /
paginate: 2


# system variables, do not change unless you knew what's it does.
paginate_path: page/:num
highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["tables"]

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

sass:
  sass_dir: _sass
  style: compressed
